version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per productid found in each orders_id
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness: 
          warn_after: {count: 90, period: day}
        
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: foreign key to ship
          - name: pdt_id
            description: foreign key to product
          - name: revenue
            description: the amount paid by the customer to purchase the product. revenue = quantity * selling_price
          - name: quantity
            description: the quantity of products purchased for a given order
        tests:
           - unique:
               column_name: "(orders_id || '-' || pdt_id)"
      - name: product
        identifier: raw_gz_product
        description: raw data of greenweez products
        columns:
          - name: products_id
            tests:
             - unique
             - not_null
      - name: ship
        identifier: raw_gz_ship
        description: raw data of greenweez shipping
        columns:
          - name: orders_id
            tests:
              - unique
              - not_null
      - name: adwords
        identifier: raw_gz_adwords
        description: adwords paid campaign performance extract
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key)"
      - name: bing
        identifier: raw_gz_bing
        description: bing paid campaign performance extract
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key)"
      - name: criteo
        identifier: raw_gz_criteo
        description: criteo paid campaign performance extract
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key)"
      - name: facebook
        identifier: raw_gz_facebook
        description: facebook paid campaign performance extract
        tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key)"

                  

