version: 2

sources: 
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: raw data of greenweez sales
      - name: product
        identifier: raw_gz_product
        description: raw data of greenweez products
      - name: ship
        identifier: raw_gz_ship
        description: raw data of greenweez shipping